version: '3.8'

services:
  csvprossessor.functionapp:
    image: ${DOCKER_REGISTRY-}csvprossessorfunctionapp
    build:
      context: .
      dockerfile: CSVProssessor.FunctionApp/Dockerfile
    ports:
      - "7071:80"
    environment:
      - CosmosDbConnectionString=AccountEndpoint=https://cosmosdb:8081/;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==;
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - csv-network

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: csvprossessor_rabbitmq_app
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"      # AMQP
      - "15672:15672"    # Management Console
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - csv-network

volumes:
  rabbitmq_data:

networks:
  csv-network:
    external: true
