version: '3.8'

services:
  csvprossessor.functionapp:
    image: ${DOCKER_REGISTRY-}csvprossessorfunctionapp
    build:
      context: .
      dockerfile: CSVProssessor.FunctionApp/Dockerfile
    ports:
      - "7071:80"
    environment:
      - CosmosDbConnectionString=AccountEndpoint=https://apps-cosmosdb-1:8081/;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==;
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    networks:
      - csv-network

networks:
  csv-network:
    external: true
